theme: jekyll-theme-minimal
title: My GitHub Site
description: A cool website for my projects.
sidebar:
  - label: Section One
    children:
      - document-one
      - document-two
      - document-three
